### ISSUE TITLE
Remove core-js from dependencies

### ISSUE THREAD

**Issue by obedparla** [insky/vue-gpickr#2]
Hey! First of all thanks for the project, it works really well and so far as been the only reliable Vue-based gradient picker I've found, kudos!

I noticed you have `core-js` included as a dependency, but I didn't find any usage of it in your code (nor should you really need it). The component right now weights 41.9kB (1) (minified and gzipped), of which 99% of it is core-js 😅.

Removing it would make it much better. Or add it as a dev-dependency if it's needed for dev for some reason. Happy to open a PR if you need it.

1) https://bundlephobia.com/result?p=vue-gpickr@0.2.5

**Comment by obedparla** [comment]
https://github.com/insky/vue-gpickr/pull/3

**Comment by insky** [comment]
Hi! Thanks for participating 😉
